// Generated by CoffeeScript 2.1.1
(function() {
  // Classe Pessoa 
  // Implementação da classe Pessoa
  var Cliente, Conta, ContaPagar, ContaReceber, Fornecedor, Pessoa, c1, c2, f1, f2, p1, p2;

  Pessoa = class Pessoa {
    construtor(nome) {
      this.nome = nome;
    }

  };

  // Classe Cliente 
  // Implementação da classe Cliente
  Cliente = class Cliente extends Pessoa {};

  // Classe Fornecedor 
  // Implementação da classe Fornecedor
  Fornecedor = class Fornecedor extends Pessoa {};

  // Classe Conta 
  // Implementação da classe Conta
  Conta = class Conta {
    construtor(descricao1, valor1, data_validade1) {
      this.descricao = descricao1;
      this.valor = valor1;
      this.data_validade = data_validade1;
    }

    conta() {}

    // some code here
    cancelar() {}

  };

  // some code here

  // Classe ContaReceber 
  // Implementação da classe ContaReceber
  ContaPagar = class ContaPagar extends Conta {
    construtor(fornecedor, descricao, valor, data_validade) {
      this.fornecedor = fornecedor;
      return super.construtor(descricao, valor, data_validade);
    }

    conta() {}

    // some code here
    cancelar() {}

  };

  
  // some code here

  // Classe ContaReceber
  // Implementação da classe ContaReceber
  ContaReceber = class ContaReceber extends Conta {
    construtor(cliente, descricao, valor, data_validade) {
      this.cliente = cliente;
      return super.construtor(descricao, valor, data_validade);
    }

    conta() {}

    // some code here 
    cancelar() {}

  };

  // some code here

  // Instancia de Cliente
  p1 = new Pessoa('Renato Franco');

  p2 = new Pessoa('Hanzo Kimura');

  // Instancia de Fornecedor 
  f1 = new Fornecedor('Coca Cola');

  f2 = new Fornecedor('Apple Inc');

  // Instancia Conta Pagar / Receber 
  c1 = new ContaPagar(f2, 'MacBook Pro Late 2018', 18.000, '26/01/2018');

  c2 = new ContaReceber(p1, 'Conta de Luz', 100.00, '18/02/2018');

  console.log(p1);

}).call(this);
